FROM --platform=linux/amd64 ubuntu:20.04 as builder
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ninja-build clang cmake

COPY . /flatcc
WORKDIR /flatcc
RUN ./scripts/build.sh

FROM ubuntu:20.04 as package
COPY --from=builder /flatcc/bin/flatcc /
